FROM cimg/android:2024.07
RUN  curl https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
RUN  sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN  sudo apt-get update
RUN  sudo apt-get install -y google-chrome-stable build-essential jq git openssh-server
RUN  sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


