FROM cimg/android:2025.10.1-node
RUN  curl https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
RUN  sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN  sudo apt-get update
RUN  sudo apt remove -y "openjdk-21-*"
RUN  sudo apt remove -y "openjdk-8-*"
RUN  sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
RUN  sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
